---

- name: Pause 5 seconds before running rest of kafka handlers
  pause:
    seconds: 5

- name: Reload firewalld for kafka service
  command: firewall-cmd --reload

- name: Start and enable kafka service
  systemd:
    name: kafka
    state: started
    enabled: yes
    daemon_reload: yes

- name: Create a symlink of kafka log directory
  file:
    src: "{{ link_path }}/logs"
    dest: "{{ log_path }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    state: link
    force: yes
