---
- name: force systemd to reread configs
  systemd:
    daemon_reload: true

- name: start and enable kafka service
  service:
    name: kafka
    state: started
    enabled: true

- name: create a symlink of kafka log directory
  file:
    src: "{{ link_path }}/logs"
    dest: "{{ log_path }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    state: link
    force: true
